# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: forecaster.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'forecaster.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66orecaster.proto\"J\n\x0f\x46orecastRequest\x12\x18\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\n.DataPoint\x12\x0f\n\x07periods\x18\x02 \x01(\x05\x12\x0c\n\x04\x66req\x18\x03 \x01(\t\"\"\n\tDataPoint\x12\n\n\x02\x64s\x18\x01 \x01(\t\x12\t\n\x01y\x18\x02 \x01(\x02\"4\n\x10\x46orecastResponse\x12 \n\x08\x66orecast\x18\x01 \x03(\x0b\x32\x0e.ForecastPoint\"Q\n\rForecastPoint\x12\n\n\x02\x64s\x18\x01 \x01(\t\x12\x0c\n\x04yhat\x18\x02 \x01(\x02\x12\x12\n\nyhat_lower\x18\x03 \x01(\x02\x12\x12\n\nyhat_upper\x18\x04 \x01(\x02\x32G\n\x14TimeSeriesForecaster\x12/\n\x08\x46orecast\x12\x10.ForecastRequest\x1a\x11.ForecastResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'forecaster_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FORECASTREQUEST']._serialized_start=20
  _globals['_FORECASTREQUEST']._serialized_end=94
  _globals['_DATAPOINT']._serialized_start=96
  _globals['_DATAPOINT']._serialized_end=130
  _globals['_FORECASTRESPONSE']._serialized_start=132
  _globals['_FORECASTRESPONSE']._serialized_end=184
  _globals['_FORECASTPOINT']._serialized_start=186
  _globals['_FORECASTPOINT']._serialized_end=267
  _globals['_TIMESERIESFORECASTER']._serialized_start=269
  _globals['_TIMESERIESFORECASTER']._serialized_end=340
# @@protoc_insertion_point(module_scope)
