# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import forecaster_pb2 as forecaster__pb2


class TimeSeriesForecasterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Forecast = channel.unary_unary(
                '/TimeSeriesForecaster/Forecast',
                request_serializer=forecaster__pb2.ForecastRequest.SerializeToString,
                response_deserializer=forecaster__pb2.ForecastResponse.FromString,
                )


class TimeSeriesForecasterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Forecast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TimeSeriesForecasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Forecast': grpc.unary_unary_rpc_method_handler(
                    servicer.Forecast,
                    request_deserializer=forecaster__pb2.ForecastRequest.FromString,
                    response_serializer=forecaster__pb2.ForecastResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TimeSeriesForecaster', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TimeSeriesForecaster(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Forecast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TimeSeriesForecaster/Forecast',
            forecaster__pb2.ForecastRequest.SerializeToString,
            forecaster__pb2.ForecastResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
